const ROLES = {
  ADMIN: 99,
  VIEWER: 1
};

const PERMISSIONS = {
  PROFILE_VIEW: "profile:view",
  PROFILE_CREATE: "profile:create",
  PROFILE_EDIT: "profile:edit",
  PROFILE_UPLOAD: "profile:upload"
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_CREATE,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.PROFILE_UPLOAD
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.PROFILE_CREATE,
    PERMISSIONS.PROFILE_EDIT,
    PERMISSIONS.PROFILE_UPLOAD
  ]
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS
};
